name: Sync Fork

on:
  schedule:
    - cron: '0 0 * * *' # once every day
  workflow_dispatch: # on button click
  push:
    paths:
      - .github/workflows/sync-main.yml

env:
  REPO: ${{ github.event.repository.name }}

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: sync fork
        run: |
          gh repo sync NCIPangea/$REPO --source CCBR/$REPO --force
